//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type HomeTradingDesk = {
  __typename?: 'HomeTradingDesk';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeTerritory = {
  __typename?: 'HomeTerritory';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  pillars?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeHighlightsItems = {
  __typename?: 'HomeHighlightsItems';
  value?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomeHighlights = {
  __typename?: 'HomeHighlights';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeHighlightsItems>>>;
};

export type HomeEfficiency = {
  __typename?: 'HomeEfficiency';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type HomeProcessesItems = {
  __typename?: 'HomeProcessesItems';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomeProcesses = {
  __typename?: 'HomeProcesses';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeProcessesItems>>>;
};

export type HomeCtaBanner = {
  __typename?: 'HomeCtaBanner';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type HomeAboutRubix = {
  __typename?: 'HomeAboutRubix';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type HomeFooterAddress = {
  __typename?: 'HomeFooterAddress';
  cities?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
};

export type HomeFooter = {
  __typename?: 'HomeFooter';
  address?: Maybe<HomeFooterAddress>;
  copyright?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  tradingDesk?: Maybe<HomeTradingDesk>;
  territory?: Maybe<HomeTerritory>;
  highlights?: Maybe<HomeHighlights>;
  efficiency?: Maybe<HomeEfficiency>;
  processes?: Maybe<HomeProcesses>;
  ctaBanner?: Maybe<HomeCtaBanner>;
  aboutRubix?: Maybe<HomeAboutRubix>;
  footer?: Maybe<HomeFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type HomeTradingDeskFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
};

export type HomeTerritoryFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  pillars?: InputMaybe<StringFilter>;
};

export type HomeHighlightsItemsFilter = {
  value?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomeHighlightsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeHighlightsItemsFilter>;
};

export type HomeEfficiencyFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type HomeProcessesItemsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomeProcessesFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeProcessesItemsFilter>;
};

export type HomeCtaBannerFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type HomeAboutRubixFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type HomeFooterAddressFilter = {
  cities?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type HomeFooterFilter = {
  address?: InputMaybe<HomeFooterAddressFilter>;
  copyright?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  tradingDesk?: InputMaybe<HomeTradingDeskFilter>;
  territory?: InputMaybe<HomeTerritoryFilter>;
  highlights?: InputMaybe<HomeHighlightsFilter>;
  efficiency?: InputMaybe<HomeEfficiencyFilter>;
  processes?: InputMaybe<HomeProcessesFilter>;
  ctaBanner?: InputMaybe<HomeCtaBannerFilter>;
  aboutRubix?: InputMaybe<HomeAboutRubixFilter>;
  footer?: InputMaybe<HomeFooterFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
};

export type HomeHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type HomeTradingDeskMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeTerritoryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  pillars?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHighlightsItemsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHighlightsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeHighlightsItemsMutation>>>;
};

export type HomeEfficiencyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProcessesItemsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProcessesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeProcessesItemsMutation>>>;
};

export type HomeCtaBannerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAboutRubixMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type HomeFooterAddressMutation = {
  cities?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type HomeFooterMutation = {
  address?: InputMaybe<HomeFooterAddressMutation>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  tradingDesk?: InputMaybe<HomeTradingDeskMutation>;
  territory?: InputMaybe<HomeTerritoryMutation>;
  highlights?: InputMaybe<HomeHighlightsMutation>;
  efficiency?: InputMaybe<HomeEfficiencyMutation>;
  processes?: InputMaybe<HomeProcessesMutation>;
  ctaBanner?: InputMaybe<HomeCtaBannerMutation>;
  aboutRubix?: InputMaybe<HomeAboutRubixMutation>;
  footer?: InputMaybe<HomeFooterMutation>;
};

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', title?: string | null, subtitle?: string | null } | null, tradingDesk?: { __typename: 'HomeTradingDesk', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null, territory?: { __typename: 'HomeTerritory', title?: string | null, subtitle?: string | null, pillars?: Array<string | null> | null } | null, highlights?: { __typename: 'HomeHighlights', title?: string | null, items?: Array<{ __typename: 'HomeHighlightsItems', value?: string | null, description?: string | null } | null> | null } | null, efficiency?: { __typename: 'HomeEfficiency', title?: string | null, subtitle?: string | null, cta?: string | null } | null, processes?: { __typename: 'HomeProcesses', title?: string | null, items?: Array<{ __typename: 'HomeProcessesItems', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null, ctaBanner?: { __typename: 'HomeCtaBanner', title?: string | null, subtitle?: string | null, cta?: string | null } | null, aboutRubix?: { __typename: 'HomeAboutRubix', title?: string | null, subtitle?: string | null, cta?: string | null } | null, footer?: { __typename: 'HomeFooter', copyright?: string | null, ctaLabel?: string | null, address?: { __typename: 'HomeFooterAddress', cities?: string | null, phone?: string | null, email?: string | null } | null } | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', title?: string | null, subtitle?: string | null } | null, tradingDesk?: { __typename: 'HomeTradingDesk', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null, territory?: { __typename: 'HomeTerritory', title?: string | null, subtitle?: string | null, pillars?: Array<string | null> | null } | null, highlights?: { __typename: 'HomeHighlights', title?: string | null, items?: Array<{ __typename: 'HomeHighlightsItems', value?: string | null, description?: string | null } | null> | null } | null, efficiency?: { __typename: 'HomeEfficiency', title?: string | null, subtitle?: string | null, cta?: string | null } | null, processes?: { __typename: 'HomeProcesses', title?: string | null, items?: Array<{ __typename: 'HomeProcessesItems', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null, ctaBanner?: { __typename: 'HomeCtaBanner', title?: string | null, subtitle?: string | null, cta?: string | null } | null, aboutRubix?: { __typename: 'HomeAboutRubix', title?: string | null, subtitle?: string | null, cta?: string | null } | null, footer?: { __typename: 'HomeFooter', copyright?: string | null, ctaLabel?: string | null, address?: { __typename: 'HomeFooterAddress', cities?: string | null, phone?: string | null, email?: string | null } | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', title?: string | null, subtitle?: string | null } | null, tradingDesk?: { __typename: 'HomeTradingDesk', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null, territory?: { __typename: 'HomeTerritory', title?: string | null, subtitle?: string | null, pillars?: Array<string | null> | null } | null, highlights?: { __typename: 'HomeHighlights', title?: string | null, items?: Array<{ __typename: 'HomeHighlightsItems', value?: string | null, description?: string | null } | null> | null } | null, efficiency?: { __typename: 'HomeEfficiency', title?: string | null, subtitle?: string | null, cta?: string | null } | null, processes?: { __typename: 'HomeProcesses', title?: string | null, items?: Array<{ __typename: 'HomeProcessesItems', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null, ctaBanner?: { __typename: 'HomeCtaBanner', title?: string | null, subtitle?: string | null, cta?: string | null } | null, aboutRubix?: { __typename: 'HomeAboutRubix', title?: string | null, subtitle?: string | null, cta?: string | null } | null, footer?: { __typename: 'HomeFooter', copyright?: string | null, ctaLabel?: string | null, address?: { __typename: 'HomeFooterAddress', cities?: string | null, phone?: string | null, email?: string | null } | null } | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    title
    subtitle
  }
  tradingDesk {
    __typename
    title
    subtitle
    features
  }
  territory {
    __typename
    title
    subtitle
    pillars
  }
  highlights {
    __typename
    title
    items {
      __typename
      value
      description
    }
  }
  efficiency {
    __typename
    title
    subtitle
    cta
  }
  processes {
    __typename
    title
    items {
      __typename
      icon
      title
      description
    }
  }
  ctaBanner {
    __typename
    title
    subtitle
    cta
  }
  aboutRubix {
    __typename
    title
    subtitle
    cta
  }
  footer {
    __typename
    address {
      __typename
      cities
      phone
      email
    }
    copyright
    ctaLabel
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  